# Welcome to Serverless!

service: serverless-step-functions-pj

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  profile: lg_sandbox # optoinal profile shold be listed in ~/.aws/credentials
  region: ${opt:region, 'us-west-2'} # optoinal
  timeout: 120
  stage: ${opt:stage, 'sandbox'}



functions:
  hello:
    handler: handler.hello
  ciao:
    handler: handler.ciao

stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: 'hello'
      definition:
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld
        States:
          HelloWorld:
            Type: Task
            Resource: "arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-hello"
            Next: CiaoWorld
          CiaoWorld:
            Type: Task
            Resource: "arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-ciao"
            End: true